#! /usr/bin/env python

import math

def main():
    # x, y, z = 0.84, 0.0, 0.989 # answer = [0.0, -1.0, 0.0]
    # x, y, z = -0.469, -0.730, 0.608 # answer = [1.0, 1.0, 1.0]
    # x, y, z = 5.0, 5.0, 5.0 # answer = None
    j1, j2, j3 = 0.0, 0.0, 0.0
    l1, l2, l3 = 0.4, 0.6, 0.4
    d = (x**2 + y**2)**0.5

    # for j1
    j1 = math.atan2(y, x)
    j1_prime = j1 - math.pi if j1 > 0 else j1 + math.pi

    # for j2
    j_prime = math.atan2(z-l1, d)
    d_prime = (d**2 + (z-l1)**2)**0.5
    ratio = (d_prime**2 + l2**2 - l3**2)/(2*d_prime*l2)
    ratio = max(-1.0, min(1.0, ratio))
    j_prime_prime = math.acos(ratio)
    j2 = math.pi/2 - (j_prime + j_prime_prime)
    j2_prime = -1 * j2

    # for j3
    ratio_2 = (l2**2 + l3**2 - d_prime**2)/(2*l2*l3)
    ratio_2 = max(-1.0, min(1.0, ratio_2))
    j_prime_prime_prime = math.acos(ratio_2)
    j3 = math.pi - j_prime_prime_prime
    j3_prime = -1 * j3

    print(j1, j2, j3)
    print(j1_prime, j2_prime, j3_prime)

if __name__ == "__main__":
    main()
