#! /usr/bin/env python

import rospy
import random
from sensor_msgs.msg import ChannelFloat32

def get_random_joint():
    return random.uniform(-2.0, 2.0)

if __name__ == "__main__":
    rospy.init_node('random_position_cmd')

    pub = rospy.Publisher('/arm_controller/position_command', ChannelFloat32, queue_size=1)
    rospy.sleep(0.5)

    msg = ChannelFloat32(values=[get_random_joint(), get_random_joint(), get_random_joint()])
    print(msg)
    pub.publish(msg)
    rospy.sleep(0.5)
    
