joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 20

joint_position:
    type: "effort_controllers/JointGroupPositionController"
    joints: [joint1, joint2, joint3]
    joint1: 
        pid: {p: 100.0, i: 0.01, d: 10.0}
    joint2: 
        pid: {p: 100.0, i: 0.01, d: 10.0}
    joint3: 
        pid: {p: 100.0, i: 0.01, d: 10.0}

# joint1_velocity:
#     type: "effort_controllers/JointVelocityController"
#     joint: joint1
#     pid: {p: 100.0, i: 0.01, d: 10.0}
# joint2_position_controller:
#     type: "effort_controllers/JointVelocityController"
#     joint: joint2
#     pid: {p: 100.0, i: 0.01, d: 10.0}
# joint3_position_controller:
#     type: "effort_controllers/JointVelocityController"
#     joint: joint3
#     pid: {p: 100.0, i: 0.01, d: 10.0}
