joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 20

joint1_velocity:
    type: "effort_controllers/JointVelocityController"
    joint: joint1
    pid: {p: 4.0, i: 100.0, d: 0.0005, i_clamp_min: -1000.0, i_clamp_max: 1000.0}
joint2_velocity:
    type: "effort_controllers/JointVelocityController"
    joint: joint2
    pid: {p: 4.0, i: 100.0, d: 0.0005, i_clamp_min: -1000.0, i_clamp_max: 1000.0}
joint3_velocity:
    type: "effort_controllers/JointVelocityController"
    joint: joint3
    pid: {p: 4.0, i: 100.0, d: 0.0005, i_clamp_min: -1000.0, i_clamp_max: 1000.0}
